#############################################################################
# Makefile for building: CashManagement
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  CashManagement.pro
# Template: app
# Command: /home/huanlu/QT/qt-5.8/5.8/gcc_64/bin/qmake -o Makefile CashManagement.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../qt-5.8/5.8/gcc_64/include -I../../qt-5.8/5.8/gcc_64/include/QtWidgets -I../../qt-5.8/5.8/gcc_64/include/QtGui -I../../qt-5.8/5.8/gcc_64/include/QtSql -I../../qt-5.8/5.8/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I. -I../../qt-5.8/5.8/gcc_64/mkspecs/linux-g++
QMAKE         = /home/huanlu/QT/qt-5.8/5.8/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = CashManagement1.0.0
DISTDIR = /home/huanlu/QT/Program/CashManagement/.tmp/CashManagement1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/huanlu/QT/qt-5.8/5.8/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/huanlu/QT/qt-5.8/5.8/gcc_64/lib -lQt5Widgets -lQt5Gui -lQt5Sql -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		mysql_connection_pool/connectionPool.cpp \
		connection_test/connectiontestthread.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		connectionPool.o \
		connectiontestthread.o \
		moc_mainwindow.o
DIST          = ../../qt-5.8/5.8/gcc_64/mkspecs/features/spec_pre.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/common/unix.conf \
		../../qt-5.8/5.8/gcc_64/mkspecs/common/linux.conf \
		../../qt-5.8/5.8/gcc_64/mkspecs/common/sanitize.conf \
		../../qt-5.8/5.8/gcc_64/mkspecs/common/gcc-base.conf \
		../../qt-5.8/5.8/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../qt-5.8/5.8/gcc_64/mkspecs/common/g++-base.conf \
		../../qt-5.8/5.8/gcc_64/mkspecs/common/g++-unix.conf \
		../../qt-5.8/5.8/gcc_64/mkspecs/qconfig.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/qt_functions.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/qt_config.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/toolchain.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/default_pre.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/resolve_config.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/default_post.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/warn_on.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/qt.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/resources.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/moc.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/unix/opengl.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/uic.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/unix/thread.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/qmake_use.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/file_copies.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/testcase_targets.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/exceptions.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/yacc.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/lex.prf \
		CashManagement.pro mainwindow.h \
		connectionPool.h \
		mysql_connection_pool/connectionPool.h \
		connection_test/connectiontestthread.h main.cpp \
		mainwindow.cpp \
		mysql_connection_pool/connectionPool.cpp \
		connection_test/connectiontestthread.cpp
QMAKE_TARGET  = CashManagement
DESTDIR       = 
TARGET        = CashManagement


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: CashManagement.pro ../../qt-5.8/5.8/gcc_64/mkspecs/linux-g++/qmake.conf ../../qt-5.8/5.8/gcc_64/mkspecs/features/spec_pre.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/common/unix.conf \
		../../qt-5.8/5.8/gcc_64/mkspecs/common/linux.conf \
		../../qt-5.8/5.8/gcc_64/mkspecs/common/sanitize.conf \
		../../qt-5.8/5.8/gcc_64/mkspecs/common/gcc-base.conf \
		../../qt-5.8/5.8/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../qt-5.8/5.8/gcc_64/mkspecs/common/g++-base.conf \
		../../qt-5.8/5.8/gcc_64/mkspecs/common/g++-unix.conf \
		../../qt-5.8/5.8/gcc_64/mkspecs/qconfig.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/qt_functions.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/qt_config.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/toolchain.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/default_pre.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/resolve_config.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/default_post.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/warn_on.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/qt.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/resources.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/moc.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/unix/opengl.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/uic.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/unix/thread.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/qmake_use.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/file_copies.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/testcase_targets.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/exceptions.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/yacc.prf \
		../../qt-5.8/5.8/gcc_64/mkspecs/features/lex.prf \
		CashManagement.pro \
		../../qt-5.8/5.8/gcc_64/lib/libQt5Widgets.prl \
		../../qt-5.8/5.8/gcc_64/lib/libQt5Gui.prl \
		../../qt-5.8/5.8/gcc_64/lib/libQt5Sql.prl \
		../../qt-5.8/5.8/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile CashManagement.pro
../../qt-5.8/5.8/gcc_64/mkspecs/features/spec_pre.prf:
../../qt-5.8/5.8/gcc_64/mkspecs/common/unix.conf:
../../qt-5.8/5.8/gcc_64/mkspecs/common/linux.conf:
../../qt-5.8/5.8/gcc_64/mkspecs/common/sanitize.conf:
../../qt-5.8/5.8/gcc_64/mkspecs/common/gcc-base.conf:
../../qt-5.8/5.8/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../qt-5.8/5.8/gcc_64/mkspecs/common/g++-base.conf:
../../qt-5.8/5.8/gcc_64/mkspecs/common/g++-unix.conf:
../../qt-5.8/5.8/gcc_64/mkspecs/qconfig.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_charts.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../qt-5.8/5.8/gcc_64/mkspecs/features/qt_functions.prf:
../../qt-5.8/5.8/gcc_64/mkspecs/features/qt_config.prf:
../../qt-5.8/5.8/gcc_64/mkspecs/linux-g++/qmake.conf:
../../qt-5.8/5.8/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../qt-5.8/5.8/gcc_64/mkspecs/features/exclusive_builds.prf:
../../qt-5.8/5.8/gcc_64/mkspecs/features/toolchain.prf:
../../qt-5.8/5.8/gcc_64/mkspecs/features/default_pre.prf:
../../qt-5.8/5.8/gcc_64/mkspecs/features/resolve_config.prf:
../../qt-5.8/5.8/gcc_64/mkspecs/features/default_post.prf:
../../qt-5.8/5.8/gcc_64/mkspecs/features/warn_on.prf:
../../qt-5.8/5.8/gcc_64/mkspecs/features/qt.prf:
../../qt-5.8/5.8/gcc_64/mkspecs/features/resources.prf:
../../qt-5.8/5.8/gcc_64/mkspecs/features/moc.prf:
../../qt-5.8/5.8/gcc_64/mkspecs/features/unix/opengl.prf:
../../qt-5.8/5.8/gcc_64/mkspecs/features/uic.prf:
../../qt-5.8/5.8/gcc_64/mkspecs/features/unix/thread.prf:
../../qt-5.8/5.8/gcc_64/mkspecs/features/qmake_use.prf:
../../qt-5.8/5.8/gcc_64/mkspecs/features/file_copies.prf:
../../qt-5.8/5.8/gcc_64/mkspecs/features/testcase_targets.prf:
../../qt-5.8/5.8/gcc_64/mkspecs/features/exceptions.prf:
../../qt-5.8/5.8/gcc_64/mkspecs/features/yacc.prf:
../../qt-5.8/5.8/gcc_64/mkspecs/features/lex.prf:
CashManagement.pro:
../../qt-5.8/5.8/gcc_64/lib/libQt5Widgets.prl:
../../qt-5.8/5.8/gcc_64/lib/libQt5Gui.prl:
../../qt-5.8/5.8/gcc_64/lib/libQt5Sql.prl:
../../qt-5.8/5.8/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile CashManagement.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../qt-5.8/5.8/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h connectionPool.h mysql_connection_pool/connectionPool.h connection_test/connectiontestthread.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp mysql_connection_pool/connectionPool.cpp connection_test/connectiontestthread.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../qt-5.8/5.8/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../../qt-5.8/5.8/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: ../../qt-5.8/5.8/gcc_64/include/QtWidgets/QMainWindow \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qmainwindow.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qtguiglobal.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qglobal.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qconfig.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qlogging.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qflags.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qatomic.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmutex.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qnumeric.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qtgui-config.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qwidget.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qwindowdefs.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qnamespace.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qobject.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstring.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qchar.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qbytearray.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qrefcount.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qarraydata.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qlist.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qiterator.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qpair.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstringlist.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qregexp.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmetatype.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qobject_impl.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmargins.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qpaintdevice.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qrect.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsize.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qpoint.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qpalette.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qcolor.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qrgb.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qrgba64.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qbrush.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qvector.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qmatrix.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qpolygon.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qregion.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qdatastream.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qiodevice.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qline.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qtransform.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qpainterpath.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qimage.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qpixelformat.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qpixmap.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qshareddata.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qhash.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qfont.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qfontmetrics.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qfontinfo.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qcursor.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qkeysequence.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qevent.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qvariant.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmap.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qdebug.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtextstream.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qlocale.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qset.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qurl.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qurlquery.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfile.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfiledevice.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qvector2d.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qtouchdevice.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qtabwidget.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qicon.h \
		mainwindow.h \
		moc_predefs.h \
		../../qt-5.8/5.8/gcc_64/bin/moc
	/home/huanlu/QT/qt-5.8/5.8/gcc_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/huanlu/QT/qt-5.8/5.8/gcc_64/mkspecs/linux-g++ -I/home/huanlu/QT/Program/CashManagement -I/home/huanlu/QT/qt-5.8/5.8/gcc_64/include -I/home/huanlu/QT/qt-5.8/5.8/gcc_64/include/QtWidgets -I/home/huanlu/QT/qt-5.8/5.8/gcc_64/include/QtGui -I/home/huanlu/QT/qt-5.8/5.8/gcc_64/include/QtSql -I/home/huanlu/QT/qt-5.8/5.8/gcc_64/include/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		../../qt-5.8/5.8/gcc_64/bin/uic
	/home/huanlu/QT/qt-5.8/5.8/gcc_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mysql_connection_pool/connectionPool.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/QtSql \
		../../qt-5.8/5.8/gcc_64/include/QtSql/QtSqlDepends \
		../../qt-5.8/5.8/gcc_64/include/QtCore/QtCore \
		../../qt-5.8/5.8/gcc_64/include/QtCore/QtCoreDepends \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qglobal.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qconfig.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qlogging.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qflags.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qatomic.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmutex.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qnumeric.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qabstractanimation.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qobject.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qnamespace.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstring.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qchar.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qbytearray.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qrefcount.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qarraydata.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qlist.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qiterator.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qpair.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstringlist.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qregexp.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmetatype.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qobject_impl.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qabstracteventdispatcher.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qeventloop.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qabstractitemmodel.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qvariant.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmap.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qdebug.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qhash.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtextstream.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qiodevice.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qlocale.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qshareddata.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qvector.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qpoint.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qset.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qabstractnativeeventfilter.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qabstractproxymodel.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qabstractstate.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qabstracttransition.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qanimationgroup.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qarraydataops.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qarraydatapointer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qbasictimer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qbitarray.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qbuffer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qbytearraymatcher.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcache.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcollator.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcommandlineoption.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcommandlineparser.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcoreapplication.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcryptographichash.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qdatastream.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qdatetime.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qdeadlinetimer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qelapsedtimer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qdir.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfileinfo.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfile.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfiledevice.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qdiriterator.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qeasingcurve.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qendian.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qeventtransition.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qexception.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfactoryinterface.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfileselector.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/QObject \
		../../qt-5.8/5.8/gcc_64/include/QtCore/QStringList \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfilesystemwatcher.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfinalstate.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfuture.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfutureinterface.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qrunnable.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qresultstore.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfuturesynchronizer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfuturewatcher.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qhistorystate.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qidentityproxymodel.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qisenum.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qitemselectionmodel.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qjsonarray.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qjsonvalue.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qjsondocument.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qjsonobject.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qlibrary.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qlibraryinfo.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qversionnumber.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qline.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qlinkedlist.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qlockfile.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qloggingcategory.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmargins.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmath.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmessageauthenticationcode.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmetaobject.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmimedata.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmimedatabase.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmimetype.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qobjectcleanuphandler.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qparallelanimationgroup.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qpauseanimation.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qplugin.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qpointer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qpluginloader.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qprocess.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qpropertyanimation.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qvariantanimation.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qqueue.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qreadwritelock.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qrect.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsize.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qregularexpression.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qresource.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsavefile.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qscopedvaluerollback.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsemaphore.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsequentialanimationgroup.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsettings.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsharedmemory.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsignalmapper.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsignaltransition.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsocketnotifier.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsortfilterproxymodel.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstack.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstandardpaths.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstate.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstatemachine.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstorageinfo.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstringlistmodel.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsystemsemaphore.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtemporarydir.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/QScopedPointer \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtemporaryfile.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtextboundaryfinder.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtextcodec.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qthread.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qthreadpool.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qthreadstorage.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtimeline.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtimer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtimezone.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtranslator.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qurl.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qurlquery.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/quuid.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qwaitcondition.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qwineventnotifier.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qxmlstream.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtcoreversion.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qtsqlglobal.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqldatabase.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqldriver.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqldriverplugin.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqlerror.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqlfield.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqlindex.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqlrecord.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqlquery.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqlquerymodel.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqlrelationaldelegate.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qitemdelegate.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qtguiglobal.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qtgui-config.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qstyleoption.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qabstractspinbox.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qwidget.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qwindowdefs.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qpaintdevice.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qpalette.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qcolor.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qrgb.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qrgba64.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qbrush.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qmatrix.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qpolygon.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qregion.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qtransform.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qpainterpath.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qimage.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qpixelformat.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qpixmap.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qfont.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qfontmetrics.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qfontinfo.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qcursor.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qkeysequence.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qevent.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qvector2d.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qtouchdevice.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qvalidator.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qicon.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qslider.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qabstractslider.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qstyle.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qtabbar.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qtabwidget.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qrubberband.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qframe.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qlistview.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qabstractitemview.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qcombobox.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqlrelationaltablemodel.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqltablemodel.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqlresult.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qtsqlversion.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/QQueue \
		../../qt-5.8/5.8/gcc_64/include/QtCore/QString \
		../../qt-5.8/5.8/gcc_64/include/QtCore/QMutex \
		../../qt-5.8/5.8/gcc_64/include/QtCore/QMutexLocker \
		connection_test/connectiontestthread.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/QThread \
		mainwindow.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/QMainWindow \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qmainwindow.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/QApplication \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qapplication.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qguiapplication.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qinputmethod.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/QPushButton \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qpushbutton.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qabstractbutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/QMainWindow \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qmainwindow.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qtguiglobal.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qglobal.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qconfig.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qlogging.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qflags.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qatomic.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmutex.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qnumeric.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qtgui-config.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qwidget.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qwindowdefs.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qnamespace.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qobject.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstring.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qchar.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qbytearray.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qrefcount.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qarraydata.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qlist.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qiterator.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qpair.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstringlist.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qregexp.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmetatype.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qobject_impl.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmargins.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qpaintdevice.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qrect.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsize.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qpoint.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qpalette.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qcolor.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qrgb.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qrgba64.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qbrush.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qvector.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qmatrix.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qpolygon.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qregion.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qdatastream.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qiodevice.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qline.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qtransform.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qpainterpath.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qimage.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qpixelformat.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qpixmap.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qshareddata.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qhash.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qfont.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qfontmetrics.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qfontinfo.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qcursor.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qkeysequence.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qevent.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qvariant.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmap.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qdebug.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtextstream.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qlocale.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qset.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qurl.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qurlquery.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfile.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfiledevice.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qvector2d.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qtouchdevice.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qtabwidget.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qicon.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

connectionPool.o: mysql_connection_pool/connectionPool.cpp mysql_connection_pool/connectionPool.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/QtSql \
		../../qt-5.8/5.8/gcc_64/include/QtSql/QtSqlDepends \
		../../qt-5.8/5.8/gcc_64/include/QtCore/QtCore \
		../../qt-5.8/5.8/gcc_64/include/QtCore/QtCoreDepends \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qglobal.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qconfig.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qlogging.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qflags.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qatomic.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmutex.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qnumeric.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qabstractanimation.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qobject.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qnamespace.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstring.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qchar.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qbytearray.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qrefcount.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qarraydata.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qlist.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qiterator.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qpair.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstringlist.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qregexp.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmetatype.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qobject_impl.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qabstracteventdispatcher.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qeventloop.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qabstractitemmodel.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qvariant.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmap.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qdebug.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qhash.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtextstream.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qiodevice.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qlocale.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qshareddata.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qvector.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qpoint.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qset.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qabstractnativeeventfilter.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qabstractproxymodel.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qabstractstate.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qabstracttransition.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qanimationgroup.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qarraydataops.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qarraydatapointer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qbasictimer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qbitarray.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qbuffer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qbytearraymatcher.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcache.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcollator.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcommandlineoption.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcommandlineparser.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcoreapplication.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcryptographichash.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qdatastream.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qdatetime.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qdeadlinetimer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qelapsedtimer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qdir.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfileinfo.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfile.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfiledevice.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qdiriterator.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qeasingcurve.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qendian.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qeventtransition.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qexception.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfactoryinterface.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfileselector.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/QObject \
		../../qt-5.8/5.8/gcc_64/include/QtCore/QStringList \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfilesystemwatcher.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfinalstate.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfuture.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfutureinterface.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qrunnable.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qresultstore.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfuturesynchronizer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfuturewatcher.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qhistorystate.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qidentityproxymodel.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qisenum.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qitemselectionmodel.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qjsonarray.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qjsonvalue.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qjsondocument.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qjsonobject.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qlibrary.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qlibraryinfo.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qversionnumber.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qline.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qlinkedlist.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qlockfile.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qloggingcategory.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmargins.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmath.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmessageauthenticationcode.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmetaobject.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmimedata.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmimedatabase.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmimetype.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qobjectcleanuphandler.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qparallelanimationgroup.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qpauseanimation.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qplugin.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qpointer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qpluginloader.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qprocess.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qpropertyanimation.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qvariantanimation.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qqueue.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qreadwritelock.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qrect.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsize.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qregularexpression.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qresource.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsavefile.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qscopedvaluerollback.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsemaphore.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsequentialanimationgroup.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsettings.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsharedmemory.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsignalmapper.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsignaltransition.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsocketnotifier.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsortfilterproxymodel.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstack.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstandardpaths.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstate.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstatemachine.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstorageinfo.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstringlistmodel.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsystemsemaphore.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtemporarydir.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/QScopedPointer \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtemporaryfile.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtextboundaryfinder.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtextcodec.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qthread.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qthreadpool.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qthreadstorage.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtimeline.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtimer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtimezone.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtranslator.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qurl.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qurlquery.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/quuid.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qwaitcondition.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qwineventnotifier.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qxmlstream.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtcoreversion.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qtsqlglobal.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqldatabase.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqldriver.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqldriverplugin.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqlerror.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqlfield.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqlindex.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqlrecord.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqlquery.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqlquerymodel.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqlrelationaldelegate.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qitemdelegate.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qtguiglobal.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qtgui-config.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qstyleoption.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qabstractspinbox.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qwidget.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qwindowdefs.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qpaintdevice.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qpalette.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qcolor.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qrgb.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qrgba64.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qbrush.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qmatrix.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qpolygon.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qregion.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qtransform.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qpainterpath.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qimage.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qpixelformat.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qpixmap.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qfont.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qfontmetrics.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qfontinfo.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qcursor.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qkeysequence.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qevent.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qvector2d.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qtouchdevice.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qvalidator.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qicon.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qslider.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qabstractslider.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qstyle.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qtabbar.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qtabwidget.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qrubberband.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qframe.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qlistview.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qabstractitemview.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qcombobox.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqlrelationaltablemodel.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqltablemodel.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqlresult.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qtsqlversion.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/QQueue \
		../../qt-5.8/5.8/gcc_64/include/QtCore/QString \
		../../qt-5.8/5.8/gcc_64/include/QtCore/QMutex \
		../../qt-5.8/5.8/gcc_64/include/QtCore/QMutexLocker \
		../../qt-5.8/5.8/gcc_64/include/QtCore/QDebug
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connectionPool.o mysql_connection_pool/connectionPool.cpp

connectiontestthread.o: connection_test/connectiontestthread.cpp connection_test/connectiontestthread.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/QThread \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qthread.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qobject.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qnamespace.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qglobal.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qconfig.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qlogging.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qflags.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qatomic.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmutex.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qnumeric.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstring.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qchar.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qbytearray.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qrefcount.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qarraydata.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qlist.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qiterator.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qpair.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstringlist.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qregexp.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmetatype.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qobject_impl.h \
		mysql_connection_pool/connectionPool.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/QtSql \
		../../qt-5.8/5.8/gcc_64/include/QtSql/QtSqlDepends \
		../../qt-5.8/5.8/gcc_64/include/QtCore/QtCore \
		../../qt-5.8/5.8/gcc_64/include/QtCore/QtCoreDepends \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qabstractanimation.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qabstracteventdispatcher.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qeventloop.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qabstractitemmodel.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qvariant.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmap.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qdebug.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qhash.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtextstream.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qiodevice.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qlocale.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qshareddata.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qvector.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qpoint.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qset.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qabstractnativeeventfilter.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qabstractproxymodel.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qabstractstate.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qabstracttransition.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qanimationgroup.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qarraydataops.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qarraydatapointer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qbasictimer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qbitarray.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qbuffer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qbytearraymatcher.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcache.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcollator.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcommandlineoption.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcommandlineparser.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcoreapplication.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qcryptographichash.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qdatastream.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qdatetime.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qdeadlinetimer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qelapsedtimer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qdir.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfileinfo.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfile.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfiledevice.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qdiriterator.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qeasingcurve.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qendian.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qeventtransition.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qexception.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfactoryinterface.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfileselector.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/QObject \
		../../qt-5.8/5.8/gcc_64/include/QtCore/QStringList \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfilesystemwatcher.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfinalstate.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfuture.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfutureinterface.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qrunnable.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qresultstore.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfuturesynchronizer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qfuturewatcher.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qhistorystate.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qidentityproxymodel.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qisenum.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qitemselectionmodel.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qjsonarray.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qjsonvalue.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qjsondocument.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qjsonobject.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qlibrary.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qlibraryinfo.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qversionnumber.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qline.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qlinkedlist.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qlockfile.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qloggingcategory.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmargins.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmath.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmessageauthenticationcode.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmetaobject.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmimedata.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmimedatabase.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qmimetype.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qobjectcleanuphandler.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qparallelanimationgroup.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qpauseanimation.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qplugin.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qpointer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qpluginloader.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qprocess.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qpropertyanimation.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qvariantanimation.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qqueue.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qreadwritelock.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qrect.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsize.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qregularexpression.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qresource.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsavefile.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qscopedvaluerollback.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsemaphore.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsequentialanimationgroup.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsettings.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsharedmemory.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsignalmapper.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsignaltransition.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsocketnotifier.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsortfilterproxymodel.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstack.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstandardpaths.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstate.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstatemachine.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstorageinfo.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qstringlistmodel.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qsystemsemaphore.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtemporarydir.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/QScopedPointer \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtemporaryfile.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtextboundaryfinder.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtextcodec.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qthreadpool.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qthreadstorage.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtimeline.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtimer.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtimezone.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtranslator.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qurl.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qurlquery.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/quuid.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qwaitcondition.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qwineventnotifier.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qxmlstream.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/qtcoreversion.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qtsqlglobal.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqldatabase.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqldriver.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqldriverplugin.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqlerror.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqlfield.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqlindex.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqlrecord.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqlquery.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqlquerymodel.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqlrelationaldelegate.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qitemdelegate.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qtguiglobal.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qtgui-config.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qstyleoption.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qabstractspinbox.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qwidget.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qwindowdefs.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qpaintdevice.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qpalette.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qcolor.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qrgb.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qrgba64.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qbrush.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qmatrix.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qpolygon.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qregion.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qtransform.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qpainterpath.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qimage.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qpixelformat.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qpixmap.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qfont.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qfontmetrics.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qfontinfo.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qcursor.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qkeysequence.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qevent.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qvector2d.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qtouchdevice.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qvalidator.h \
		../../qt-5.8/5.8/gcc_64/include/QtGui/qicon.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qslider.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qabstractslider.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qstyle.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qtabbar.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qtabwidget.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qrubberband.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qframe.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qlistview.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qabstractitemview.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		../../qt-5.8/5.8/gcc_64/include/QtWidgets/qcombobox.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqlrelationaltablemodel.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqltablemodel.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qsqlresult.h \
		../../qt-5.8/5.8/gcc_64/include/QtSql/qtsqlversion.h \
		../../qt-5.8/5.8/gcc_64/include/QtCore/QQueue \
		../../qt-5.8/5.8/gcc_64/include/QtCore/QString \
		../../qt-5.8/5.8/gcc_64/include/QtCore/QMutex \
		../../qt-5.8/5.8/gcc_64/include/QtCore/QMutexLocker
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connectiontestthread.o connection_test/connectiontestthread.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

